version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./shared:/app/shared
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./shared:/app/shared

volumes:
  mongo-data:
