version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/extensionDB
    volumes:
      - ./shared:/app/shared
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./shared:/app/shared

volumes:
  mongo-data:
  redis-data:
