name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}
    - name: Debug SSH Connection
      run: |
        echo "Testing SSH connection..."
        echo "$AWS_USERNAME"
        echo "$AWS_HOST"

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.AWS_USERNAME }}@${{ env.AWS_HOST }} << 'EOF'
          # Navigate to the project directory
          cd siteanalyzer-be

          # Pull the latest changes
          git pull origin main

          # Install dependencies and restart the application
          docker-compose down
          docker-compose up -d --build
        EOF
